name: 🚀 Feature Request
description: Suggest an idea to help us improve the package
title: "[🚀]: "
labels: ["enhancement"]
body:
- type: markdown
  attributes:
    value: Thank you for taking the time to fill out this feature request report!
- type: textarea
  attributes:
    label: Barriers / Obstacles
    placeholder: A concise description of what you're trying to improve.
- type: textarea
  attributes:
    label: Suggested Solution
    placeholder: (required) A concise description of what you wish to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternatives
    placeholder: A concise description of any alternative solutions or features you've considered.
- type: textarea
  attributes:
    label: Anything else?
    description: Links? References? Anything that will give us more context about the issue you are encountering!
    placeholder: You can attach images or log files by clicking this area to highlight it and then dragging files in.
